### ISSUE TITLE
Some Subscribed channels not working

### ISSUE THREAD

**Issue by rehank3g** [ForceGT/Tata-Sky-IPTV#3]
Some channels not working like Sony BBC Earth HD.. can you please check and fix the issue.

**Comment by ForceGT** [comment]
Only channels that you have subscribed to in the Tata Sky portal will work
If you find some channel that doesn't work kindly check if you've subscribed

Another reason could be that the `allChannels.json` file which I included here may have changed
You can run the `allChannels.py` script using `python allChannels.py` to generate it again..Takes only a few seconds to a minute

Let me know if this fixes your problem

**Comment by rehank3g** [comment]
Sony BBC Earth is already subscribed. I tried to regenerate all channels.json file but getting error as shown in snap shot
![IMG_20210328_230636](https://user-images.githubusercontent.com/56449037/112761722-479db780-901a-11eb-9670-71ce43bd4d0c.jpg)

**Comment by ForceGT** [comment]
Looks like some script issue
Let me get to my laptop and I'll get back

**Comment by ForceGT** [comment]
Try again I commited some changes 
If not then [here](https://pastebin.com/XPmA4CXD) is the allChannels.json file which is freshly generated

Actually I am in the process of making some changes to the method of authentication and stuff so that you don't have to generate a playlist everyday but currently I am little busy so here is what I can do currently

**Comment by rehank3g** [comment]
Thanks a lot 🙏 allchannels.py working now and also subscribed channels started working.

I faced one more issue earlier.. login via OTP was not working for me so I logged in via SID and password.
