### ISSUE TITLE
How to get SessionId and Ticket

### ISSUE THREAD

**Issue by gadhiamitul41** [ForceGT/Tata-Sky-IPTV#4]
Can you give me some details how can I get the SessionId and Ticket as shown in the flow chart?

**Comment by ForceGT** [comment]
Ah well I am sorry for that, I have decided to keep it private because Tata Sky web and mobile apps do not use it anymore
There is a possibility for DMCA, so just use whatever I have posted that is good enough
I might find a backend for this script also so that all the generation and re generation is done on the server side only

**Comment by gadhiamitul41** [comment]
Can we get in touch on discord or any other platform?
